services:
  server:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
      # Uncomment for Development
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - db
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
      # Uncomment for Development
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_COMFIG:-serverName=docker}
      XDEBUG_MODE: ${XDEBUG_MODE:-debug}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_TRIGGER: 'yes'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${SQL_DATABASE}
      MARIADB_USER: ${SQL_USER}
      MARIADB_PASSWORD: ${SQL_PASSWORD}
    ports:
      - '${SQL_PORT}:3306'
    healthcheck:
      test: "exit 0"
    volumes:
      - db:/var/lib/mysql
      - ./dumps:/opt/dumps
volumes:
  db:
